export { BaseError } from './base-error'
export { isCausable, type Causable } from './lib/is-causable'
export { type Codable, isCodable } from './lib/is-codable'
export { isError } from './lib/is-error'
export { catchError, asyncCatchError } from './lib/catch-error'
